---
sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.4.1
env:
  global:
    - OS_NAME=centos
  matrix:
    - OS_MAJOR_VERSION=6
    - OS_MAJOR_VERSION=7
addons:
  apt:
    packages:
      - shellcheck
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version
install:
  - gem install mdl
before_script:
# syntax, linting and pre-test stages
  - mdl -s relaxed README.md
  - shellcheck -e SC2034 -e SC2181 src/check_oneprovider
  - shellcheck -e SC2034 -e SC2181 src/check_onezone
  - docker build -t onedata-nagios-test -f docker/Dockerfile.nginx .
script:
# Actual testing of the product
# First, start the build container
  - docker run --name build_container -d -ti -v $PWD:/tmp -w /tmp $OS_NAME:$OS_MAJOR_VERSION /bin/bash -c 'while true ; do sleep 1000 ; done'
# Now, install prerequisites for the build
  - docker exec -i -w /root build_container yum install -y rpm-build make
# and ensure the build paths are present
  - docker exec -i -w /root build_container bash -c 'mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}'
# make the tarball  
  - docker exec -i -w /tmp build_container make
# and copy it to the place rpmbuild expects it
  - docker exec -i -w /tmp build_container cp nagios-plugins-onedata*tar.gz /root/rpmbuild/SOURCES
# now build the rpm
  - docker exec -i -w /tmp build_container rpmbuild -bb nagios-plugins-onedata.spec
# and install it
  - docker exec -i -w /root/rpmbuild/RPMS/noarch build_container rpm -Uvh nagios-plugins-onedata-3.2.0-1.el${OS_MAJOR_VERSION}.noarch.rpm
# now see if it runs
  - docker exec -ti build_container bash /usr/lib64/argo-monitoring/probes/org.onedata/check_onezone -h
# if it works, get the rpm we just built to the shared volume
  - docker exec -ti build_container bash -c 'cp -v /root/rpmbuild/RPMS/noarch/*.rpm /tmp'
#  - tests/test.sh
before_cache:
after_success:
# create the rpm with the correct name, pulling out version and OS
# WIP on https://github.com/onedata/nagios-plugins-onedata/issues/8
  - echo "not implemented yet"
after_failure:
before_deploy:
deploy:
  provider: releases
  api_key:
  file:
    - nagios-plugins-onedata-3.2.0-1.el${OS_MAJOR_VERSION}.noarch.rpm
  on:
    tags: true
after_deploy:
after_script:
